//
// Generated file, do not edit! Created by opp_msgtool 6.0 from src/node_bus/apps/AirPollutionMessage.msg.
//

#ifndef __AIRPOLLUTIONMESSAGE_M_H
#define __AIRPOLLUTIONMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class AirPollutionMessage;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>src/node_bus/apps/AirPollutionMessage.msg:19</tt> by opp_msgtool.
 * <pre>
 * class AirPollutionMessage extends inet::FieldsChunk
 * {
 *     string rawPayload;
 * }
 * </pre>
 */
class AirPollutionMessage : public ::inet::FieldsChunk
{
  protected:
    omnetpp::opp_string rawPayload;

  private:
    void copy(const AirPollutionMessage& other);

  protected:
    bool operator==(const AirPollutionMessage&) = delete;

  public:
    AirPollutionMessage();
    AirPollutionMessage(const AirPollutionMessage& other);
    virtual ~AirPollutionMessage();
    AirPollutionMessage& operator=(const AirPollutionMessage& other);
    virtual AirPollutionMessage *dup() const override {return new AirPollutionMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getRawPayload() const;
    virtual void setRawPayload(const char * rawPayload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AirPollutionMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AirPollutionMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline AirPollutionMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<AirPollutionMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __AIRPOLLUTIONMESSAGE_M_H

